[GOV- 267] Changing custom data type to array
openMF/ph-ee-connector-common pull request #32
Opened 2023-04-27 09:00 UTC by truthfool

## Description

- Changing custom data type to array
Jira Ticket : https://mifosforge.jira.com/browse/GOV-267

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-04-27 09:00 UTC, truthfool commented
@fynmanoj @avikganguly01

2023-05-16 12:07 UTC, fynmanoj requested changes
how is this related to https://mifosforge.jira.com/browse/GOV-267

2023-05-16 15:10 UTC, truthfool commented
> how does that connected to https://mifosforge.jira.com/browse/GOV-267

The array of custom data gets published.

2023-05-23 09:23 UTC, fynmanoj approved these changes

2023-05-23 09:24 UTC, fynmanoj commented on src/main/java/org/mifos/connector/common/channel/dto/TransactionChannelRequestDTO.java
> +    private List<CustomData> customData;
the naming convention is wrong

2023-05-23 09:25 UTC, merged