GOV: 293 JWS implementation for callback scenario
openMF/ph-ee-connector-common pull request #35
Opened 2023-05-02 12:20 UTC by danishjamal104

## Description

* Implemented new route which can be used for setting up the JWS signature just before sending out the API request (callback).

For more info refer [GOV-293](https://mifosforge.jira.com/browse/GOV-293?atlOrigin=eyJpIjoiOGE5ZThkOGFlMmY5NDlkNWI3NTJlZDU2NzY4YzU2MmUiLCJwIjoiaiJ9).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Design related bullet points or design document link related to this PR added in the description above. 

- [x] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [x] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-05-02 13:02 UTC, fynmanoj requested changes
reset version to 1.5.0

2023-05-03 06:03 UTC, danishjamal104 commented on build.gradle
> +version = '1.5.1-SNAPSHOT'
ok

2023-05-16 17:01 UTC, fynmanoj requested changes
revisit the hashmap logic for storing the tenant details in memory

2023-05-17 09:47 UTC, danishjamal104 commented on src/main/java/org/mifos/connector/common/camel/JWSProcessor.java
> +        String signatureData = webSignatureInterceptor.getDataToBeHashed(headers, body);
done

2023-05-17 09:47 UTC, danishjamal104 commented on src/main/java/org/mifos/connector/common/camel/JWSProcessor.java
> +        exchange.getIn().setHeader(Constant.HEADER_JWS, signature);
Discussed async. We can avoid this for now.

2023-05-18 09:27 UTC, fynmanoj approved these changes
LGTM

2023-05-18 09:27 UTC, merged